name: Generate Go Files and Commit

on:
  push:
    branches:
      - main
      - master

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: |
          go mod download

      - name: Generate Go files from proto
        run: |
          make generate

      - name: Configure git
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes and commit
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "Auto-generate Go files from proto on push to main/master"
          else
            echo "No changes to commit"
          fi

      - name: Tag the new commit
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
          git tag -a $TAG_NAME -m "Auto-generated tag for proto generation"

      - name: Push the commit and tag using the token
        run: |
          git push https://x-access-token:${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main
          git push https://x-access-token:${{ secrets.GH_PAT_TOKEN }}@github.com/${{ github.repository }} $TAG_NAME
